
name: llava_deploy
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.0.1   # PyTorch 2.x with CUDA support
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - pip
  - pip:
      - torchaudio==2.0.2
      - transformers>=4.33
      - accelerate>=0.20
      - bitsandbytes>=0.39.0
      - gradio>=3.31
      - Pillow>=9.0
      - huggingface_hub>=0.15
      - numpy>=1.20
      - scipy>=1.5
      # - flash-attn  (Optional: for supported GPUs, can be installed separately)
      # - ninja       (Optional: for flash-attn build)
