
name: llava_deploy
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - pip
  - pip:
      - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
      - torchaudio==2.0.2
      - transformers>=4.33
      - accelerate>=0.20
      - bitsandbytes>=0.39.0
      - gradio>=3.31
      - Pillow>=9.0
      - huggingface_hub>=0.15
      - numpy>=1.20
      - scipy>=1.5
